#!/usr/bin/env python3

import random

# These functions were inspired by Ruby functions generated by ChatGPT
def chess_square_color(coord):
    x = (ord(coord[0]) - ord('a')) + 1
    y = int(coord[1]) - 1
    return "light" if (x + y) % 2 == 0 else "dark"

def random_chess_coordinate():
    x = random.randint(0, 7)
    y = random.randint(0, 7)
    return chr(x + ord('a')) + str(y + 1)

while True:
    coord = random_chess_coordinate()
    guess = input("What color is " + coord + "? ")

    # TODO: Add a little validation to the input
    if guess == "0":
        break
    elif guess == chess_square_color(coord):
        print("Correct!")
    else:
        print("Wrong you fool!")

    # Add newline for separation/cleanliness
    print("")
