#!/usr/bin/env ruby

# These two methods were generated by ChatGPT, rather brilliantly I think. The
# explanation was also provided by ChatGPT.

# In this script, the chess_square_color function takes a single argument, a
# string representing the chess coordinate. It then uses the ord method to get
# the ASCII value of the first character of the coordinate (the letter) and
# subtracts the ASCII value of 'a' (97) to get the x-coordinate. The second
# character of the coordinate (the number) is converted to an integer using
# to_i and decremented by 1 to get the y-coordinate. Then it uses modulus
# operator to check if x+y is even or odd and based on that it returns "light"
# or "dark".

# Note from me: the AI didn't include '+ 1' for the x coordinate, which messed
# up the calculation - if we assume a,c,e,g are 'odd' numbers and odd with odd
# == dark. An odd number + odd number is an even number. IOW, `a` needs to be 1
# not 0, then the odd/even test works correctly.
def chess_square_color(coordinate)
  x = (coordinate[0].ord - 'a'.ord) + 1
  y = coordinate[1].to_i - 1
  (x + y) % 2 == 0 ? "light" : "dark"
end

# In this script, the `random_chess_coordinate` function uses `sample` method to
# select a random letter from an array of letters "a" to "h" and assigns it to
# the variable `x`. Then it uses `rand` method to generate a random number between
# 1 and 8, assigns it to the variable `y`, and concatenates the letter and number
# to form a chess coordinate.

# This function will return a random chess coordinate in the format of "a1",
# "b3", etc.  Please keep in mind that rand method is not cryptographically
# secure, if you are using it in security-sensitive applications, you should
# use more secure method like `SecureRandom.random_number`.
def random_chess_coordinate
  letters = ('a'..'h').to_a
  x = letters.sample
  y = rand(1..8)
  "#{x}#{y}"
end

puts "This game will test your knowledge of what color each square of a chess board"
puts "is. Doing this without looking at a chess board will help visualize the"
print "board in your mind.\n\n"
print "Enter 0 to quit.\n\n"

while true
  coord = random_chess_coordinate

  print "What color is #{coord}? "
  guess = gets.chomp.downcase

  if guess == '0'
    break
  elsif not (guess == 'light' or guess == 'dark')
    puts "Invalid response. Valid responses are light or dark."
  end

  if guess == chess_square_color(coord)
    puts "Correct!"
  else
    puts "Wrong you fool!"
  end

  # Newline for separation and cleanliness
  print "\n"
end
